---
- hosts: all
  become: true
  tasks:
    - name: updating repository index
      become: true
      apt:
        update_cache: true
      when: ansible_distribution in ["Ubuntu","Debian"]

    - name: "install apache2 package"
      apt:
        name: apache2
        state: latest
      when: ansible_distribution in ["Ubuntu","Debian"]

    - name: add php support for apache
      apt:
        name: libapache2-mod-php
        state: latest
      when: ansible_distribution in ["Ubuntu","Debian"]
