---

- hosts: all
  become: true
  tasks:

  - name: updating repository index
    apt:
      update_cache: true
    when: ansible_distribution in ["Ubuntu","Debian"]

  - name: remove apache2 package
    apt:
      name: nginx
      state: absent
    when: ansible_distribution in ["Ubuntu","Debian"]

  - name: remove php support for apache
    apt:
      name: libapache2-mod-php
      state: absent
